---
title: "Modelos de Regresión No Lineales en Ventas de Videojuegos"
output: html_document
---

```{r setup, include=FALSE}
# Cargamos las bibliotecas necesarias
library(tidyverse)
library(knitr)
library(rmarkdown)
library(broom)
library(ggplot2)
```

```{r datos}	
# Leemos el fichero csv
videojuegos <- read.csv("vgsales.csv", header = TRUE)
# Mostramos las primeras líneas del conjunto de datos
head(videojuegos)
```

```{r}
# Eliminamos las filas con valores desconocidos (NAs)
videojuegos <- videojuegos %>% drop_na()

# Mostramos las primeras líneas después de preprocesamiento
head(videojuegos)
```

```{r}
# Construimos un modelo de regresión lineal simple
model <- lm(Global_Sales ~ Year, data = videojuegos)

# Mostramos un resumen del modelo
summary(model)
```

```{r}
# Interpretamos el modelo
tidy_model <- tidy(model)

# El coeficiente de "Year" nos dice cuánto cambia en promedio la variable dependiente (Global_Sales)
# por cada aumento de una unidad en "Year", manteniendo todas las demás variables constantes.
tidy_model
```

```{r}
# Creamos un gráfico de dispersión con la línea de regresión
ggplot(videojuegos, aes(x = Year, y = Global_Sales)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE, color = "red")
```